Resources:
  GroupsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      groupsTableName: ${self:custom.groupsTableName}
      AttributeDefinitions:
        - AttributeName: groupName
          AttributeType: S
      KeySchema:
        - AttributeName: groupName
          KeyType: HASH
      # Set the capacity to auto-scale
      BillingMode: PAY_PER_REQUEST
